name: Trigger auto deployment for amar-con-app-monorepo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/amar-con-app-monorepo-AutoDeployTrigger-5ebf7089-cf0d-449a-801f-fe01c7210918.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AMARCONAPPMONOREPO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AMARCONAPPMONOREPO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AMARCONAPPMONOREPO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: amarreg.azurecr.io
          registryUsername: ${{ secrets.AMARCONAPPMONOREPO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AMARCONAPPMONOREPO_REGISTRY_PASSWORD }}
          containerAppName: amar-con-app-monorepo
          resourceGroup: amar-con-env-1
          imageToBuild: amarreg.azurecr.io/amar-con-app-monorepo:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


