name: Trigger auto deployment for amar-con-app-ws-1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/amar-con-app-ws-1-AutoDeployTrigger-6935d000-dd4f-49c7-8f46-db85906a4669.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AMARCONAPPWS1_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AMARCONAPPWS1_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AMARCONAPPWS1_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: amarreg.azurecr.io
          registryUsername: ${{ secrets.AMARCONAPPWS1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AMARCONAPPWS1_REGISTRY_PASSWORD }}
          containerAppName: amar-con-app-ws-1
          resourceGroup: amar-con-env
          imageToBuild: amarreg.azurecr.io/amar-con-app-ws-1:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


